### ISSUE TITLE
Not responding to request for unsupported domain

### ISSUE THREAD

**Issue by wmurphyrd** [small-tech/auto-encrypt#3]
Hey @aral! I wanted to give this a try for an upcoming certificate expiration https://gup.pe. I setup autoencrypt using default settings, but it only filled my log with this message:

`   🤨    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain gup.pe (valid domains are gup,www.gup).`

You can see how I'm using it here: https://github.com/wmurphyrd/guppe/blob/autoencrypt/index.js#L69

Is it just not recognizing my uncommon tld as a valid one?

**Comment by wmurphyrd** [comment]
I just needed to specify the domain in the options. Works great! Gonna be converting all my projects to this. Thanks.

**Comment by aral** [comment]
Glad you sorted it out. The initial issue was likely due to your server’s hostname being gup instead of gup.pe. It uses the hostname by default if no domains are specified.
